### PR TITLE
Migrate to ESLint Flat configs and use reviewable-configs (nodefire)

### PR DESCRIPTION
**Pull request by snoack**
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`package.json` line 42 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O771Woj7e-XIlaoaviK:-O771Woj7e-XIlaoaviL:b-gj1awo) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/package.json#L42)):*
> ```JSON
>     "lru-cache": "6.x",
>     "safe-timers": "^1.1.0",
>     "tsconfig-reviewable": "../reviewable-configs/tsconfig/"
> ```

Is it possible not to rely on checked out copies of the repo?  Doing so would impact build actions and make it harder for folks to set up their dev environments.  I thought you could point these directly at GitHub repos?

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @pkaminski)

___
*[`package.json` line 42 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O77-Fsy5IS0xMgQmPJP:-O77-Fsy5IS0xMgQmPJQ:b-rsxut8) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/package.json#L42)):*
> ```JSON
>     "lru-cache": "6.x",
>     "safe-timers": "^1.1.0",
>     "tsconfig-reviewable": "../reviewable-configs/tsconfig/"
> ```

TODO: Update once reviewable-config repo is published.
___
*[`package.json` line 42 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O771Woj7e-XIlaoaviK:-O7744hD-xY--rI_7_gs:bqfigp6) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/package.json#L42)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Is it possible not to rely on checked out copies of the repo?  Doing so would impact build actions and make it harder for folks to set up their dev environments.  I thought you could point these directly at GitHub repos?
</blockquote></details>

Yes, this is just temporarily.
___
*[`tsconfig.json` line 2 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O77-Tzq4lSma0i7RfGa:-O77-Tzr4zJvDFNgwOJp:bluttjj) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L2)):*
> ```jsonc
> {
>     "extends": "tsconfig-reviewable/tsconfig.json",
> ```

I used the `tsconfig.json` from `reviewable-server` as baseline for the shared config. Remaining below are option that were different for `nodefire`.
___
*[`tsconfig.json` line 4 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O770IDAAU2Se2-Ljf4K:-O770IDB89QDtMrTELVN:b-p5licy) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L4)):*
> ```jsonc
>     "extends": "tsconfig-reviewable/tsconfig.json",
>     "compilerOptions": {
>         "allowJs": false /* Allow javascript files to be compiled. */,
> ```

It seems all this does is keep TypeScript from processing the JavaScript files in `/tests/`. Adding `"./tests"` to `excludes` seems to have the same effect.
___
*[`tsconfig.json` line 5 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O77-ydI3xwpErKqRM4x:-O77-ydI3xwpErKqRM4y:b-yfl82l) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L5)):*
> ```jsonc
>     "compilerOptions": {
>         "allowJs": false /* Allow javascript files to be compiled. */,
>         "declaration": true /* Generate declaration files alongside with js files? */,
> ```

I guess generating declaration files is somewhat library specific, and therefore it makes sense to override this option here, right?
___
*[`tsconfig.json` line 8 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O770mQ-ETerQYY6ycMS:-O770mQ0EDe-8ihY9O_d:b2dxfda) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L8)):*
> ```jsonc
>         "outDir": "./built" /* Redirect output structure to the directory. */,
>         "rootDir": "./src/" /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */,
>         "target": "ES2016" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */,
> ```

Without overriding `target` we'd default to `"target" : 2021` from the shared config which will cause the generated code to use the `.?` operator. That seems to be the only difference in the output.

Does `nodefire` only run on Node.js or also in the browser? In the latter case I guess it would make sense to target an older version here for compatibility with legacy browsers?
___
*[`tsconfig.json` line 9 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O772Lqw7jN87upY4DK-:-O772Lqw7jN87upY4DK0:bu6vs22) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L9)):*
> ```jsonc
>         "rootDir": "./src/" /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */,
>         "target": "ES2016" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */,
>         "skipLibCheck": true,
> ```

This speeds up build time of `nodefire`. On my laptop with `"skipLibCheck": true` it builds in ~1.6s, otherwise ~3.6s.

I also tried this option in `reviewable-server` but it makes no measurable difference there. Therefore I see how the use case is project specific. What do you think?
___
*[`tsconfig.json` line 10 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O773HXN3yIlIHGGPAYV:-O773HXN3yIlIHGGPAYW:b-tsluiu) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L10)):*
> ```jsonc
>         "target": "ES2016" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */,
>         "skipLibCheck": true,
>         "sourceMap": false
> ```

It doesn't seem to effect the build time too much. On my laptop enabling source maps increases the build time from ~1.6s to just ~1.75s. Generally, having source maps for generated code can be useful for debugging. Not sure why it was disabled here?

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @pkaminski)

___
*[`tsconfig.json` line 5 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O77-ydI3xwpErKqRM4x:-O775H-p7-X4DV5Obr-9:budof29) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L5)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

I guess generating declaration files is somewhat library specific, and therefore it makes sense to override this option here, right?
</blockquote></details>

library specific -> specific to library projects
___
*[`tsconfig.json` line 10 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O773HXN3yIlIHGGPAYV:-O774z_n8x_Y7plRmNr5:b-lodfxn) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L10)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

It doesn't seem to effect the build time too much. On my laptop enabling source maps increases the build time from ~1.6s to just ~1.75s. Generally, having source maps for generated code can be useful for debugging. Not sure why it was disabled here?
</blockquote></details>

Well, technically it wasn't disabled here but it was enabled in`reviewable-server` only.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @snoack)

___
*[`tsconfig.json` line 4 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O770IDAAU2Se2-Ljf4K:-O774gNg8F2v-yPquzLN:b-u0fmvz) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L4)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

It seems all this does is keep TypeScript from processing the JavaScript files in `/tests/`. Adding `"./tests"` to `excludes` seems to have the same effect.
</blockquote></details>

Seems right to me.
___
*[`tsconfig.json` line 5 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O77-ydI3xwpErKqRM4x:-O774kLK43eVZ6ybHq4E:b-vk9mis) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L5)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

library specific -> specific to library projects
</blockquote></details>

Yes, though perhaps we want a shared `tsconfig` for libraries (inheriting from the main one) if multiple ones will need the same tweaks?
___
*[`tsconfig.json` line 8 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O770mQ-ETerQYY6ycMS:-O774zrh21rhq0p5dNLn:b-la8jls) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L8)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Without overriding `target` we'd default to `"target" : 2021` from the shared config which will cause the generated code to use the `.?` operator. That seems to be the only difference in the output.

Does `nodefire` only run on Node.js or also in the browser? In the latter case I guess it would make sense to target an older version here for compatibility with legacy browsers?
</blockquote></details>

`nodefire` is purely Node.js, so it's fine to target new versions aggressively.  Just keep in mind to update the `engines` field in `package.json` and keep it no newer than the oldest currently supported LTS version.
___
*[`tsconfig.json` line 9 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O772Lqw7jN87upY4DK-:-O775TvG9Bvbeo11hRqy:b-20uhhu) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L9)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

This speeds up build time of `nodefire`. On my laptop with `"skipLibCheck": true` it builds in ~1.6s, otherwise ~3.6s.

I also tried this option in `reviewable-server` but it makes no measurable difference there. Therefore I see how the use case is project specific. What do you think?
</blockquote></details>

I'm not an expert on `tsc` options so I don't know what the semantic impact of this would be.  The docs appear to imply that you shouldn't need to set this flag.  I'm not at all concerned with saving a few seconds of build time.
___
*[`tsconfig.json` line 10 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O773HXN3yIlIHGGPAYV:-O775lJt0mi9VKdckRTN:bg0ql1z) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L10)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Well, technically it wasn't disabled here but it was enabled in`reviewable-server` only.
</blockquote></details>

I think it's fine to generate sourcemaps by default for all projects.

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @pkaminski)

___
*[`tsconfig.json` line 4 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O770IDAAU2Se2-Ljf4K:-O777SxP4mCkfLuYPOaA:b-tx5wc2) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L4)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Seems right to me.
</blockquote></details>

Alright, I removed this option in favor of `excludes` for a more unified configuration.
___
*[`tsconfig.json` line 5 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O77-ydI3xwpErKqRM4x:-O776f8S8I2vFYLkOE6Q:bt006je) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L5)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Yes, though perhaps we want a shared `tsconfig` for libraries (inheriting from the main one) if multiple ones will need the same tweaks?
</blockquote></details>

Do we current have any repos other than `reviewable-server` and `nodefire` using TypeScript?
___
*[`tsconfig.json` line 8 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O770mQ-ETerQYY6ycMS:-O778Zzh1000Y4toOn9J:b-z0wvy0) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L8)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

`nodefire` is purely Node.js, so it's fine to target new versions aggressively.  Just keep in mind to update the `engines` field in `package.json` and keep it no newer than the oldest currently supported LTS version.
</blockquote></details>

Ok, done. I updated `engines.node` to `14.0` as per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility).
___
*[`tsconfig.json` line 9 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O772Lqw7jN87upY4DK-:-O779KEp7uwYpeNj8tcZ:bdz3sbj) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L9)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I'm not an expert on `tsc` options so I don't know what the semantic impact of this would be.  The docs appear to imply that you shouldn't need to set this flag.  I'm not at all concerned with saving a few seconds of build time.
</blockquote></details>

I also only know what the docs say in regard of `skipLibCheck`. FWIW, this option does not effect the output at all, but it can cause the build to fail if there are issues in the type definitions of libraries you use. So it's pretty safe to turn it on or off, and `nodefire` just builds fine either way.

I'm undecided, but I guess if we don't care about 2s in difference of build time it isn't worth an override. So I'm in favor of either moving it to the shared config or not using it at all for consistency.
___
*[`tsconfig.json` line 10 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O773HXN3yIlIHGGPAYV:-O77BTIjBK-e6fWzt3A3:blakgz4) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L10)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I think it's fine to generate sourcemaps by default for all projects.
</blockquote></details>

Alright, I removed the override here.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: all files reviewed, 3 unresolved discussions (waiting on @snoack)

___
*[`tsconfig.json` line 5 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O77-ydI3xwpErKqRM4x:-O77LrBuA9jEX8f8RLMH:b-pmtyzh) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L5)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Do we current have any repos other than `reviewable-server` and `nodefire` using TypeScript?
</blockquote></details>

`cinderbase`, though it's not a library.  I wouldn't be surprised if we wanted to port more of the `fire*` stuff to TS in the future but perhaps it's premature optimization.  Your call.
___
*[`tsconfig.json` line 8 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O770mQ-ETerQYY6ycMS:-O77MUZV7d4rCSE_Ko0B:bt9ze02) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L8)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Ok, done. I updated `engines.node` to `14.0` as per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility).
</blockquote></details>

That technically requires a major version bump.
___
*[`tsconfig.json` line 9 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O772Lqw7jN87upY4DK-:-O77Maks3a91sntBf4nA:b-a6i5cn) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L9)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

I also only know what the docs say in regard of `skipLibCheck`. FWIW, this option does not effect the output at all, but it can cause the build to fail if there are issues in the type definitions of libraries you use. So it's pretty safe to turn it on or off, and `nodefire` just builds fine either way.

I'm undecided, but I guess if we don't care about 2s in difference of build time it isn't worth an override. So I'm in favor of either moving it to the shared config or not using it at all for consistency.
</blockquote></details>

I'd lean towards leaving it out.  Stick with the default settings unless there's a good reason to customize.

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`tsconfig.json` line 5 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O77-ydI3xwpErKqRM4x:-O77Ul7T79ksl76sUPtw:b-x69lco) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L5)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

`cinderbase`, though it's not a library.  I wouldn't be surprised if we wanted to port more of the `fire*` stuff to TS in the future but perhaps it's premature optimization.  Your call.
</blockquote></details>

Let's abstract things then when we get there.
___
*[`tsconfig.json` line 8 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O770mQ-ETerQYY6ycMS:-O77UVKV8HWCD1aAhnU8:b-tfvj7d) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L8)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

That technically requires a major version bump.
</blockquote></details>

Right. Let's do it then next time we have to bump the major version any way. I reverted the change for now.
___
*[`tsconfig.json` line 9 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O772Lqw7jN87upY4DK-:-O77TDVY9DyouIyf71UG:b-2cizva) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/tsconfig.json#L9)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I'd lean towards leaving it out.  Stick with the default settings unless there's a good reason to customize.
</blockquote></details>

Ok, done. Though, FWIW, most TypeScript options' default value is not  the default because it's the recommended configuration but for backwards compatibility.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: all files reviewed, 2 unresolved discussions (waiting on @snoack)

___
*[`eslint.config.mjs` line 11 at r4](https://reviewable.io/reviews/Reviewable/nodefire/43#-O7onw8O6AOlFFVVRB1B:-O7onw8P2UAbCYJ3Eb13:b4ycqh6) ([raw file](https://github.com/Reviewable/nodefire/blob/80988d865df7ad455195b7dad24ddd266a390086/eslint.config.mjs#L11)):*
> ```JavaScript
>   ...reviewableConfigTypescript,
>   {
>     languageOptions: {
> ```

Would it make sense to make a `node-server` configuration upstream that includes all of the above and these `languageOptions`?  Ideally I think we'd like packages to use fully predefined configs as much as possible, while leaving the door open to customization for oddballs like Hubkit.

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @pkaminski)

___
*[`eslint.config.mjs` line 11 at r4](https://reviewable.io/reviews/Reviewable/nodefire/43#-O7onw8O6AOlFFVVRB1B:-O7ooiaZ0BUvDQKOiCnk:begw0lt) ([raw file](https://github.com/Reviewable/nodefire/blob/80988d865df7ad455195b7dad24ddd266a390086/eslint.config.mjs#L11)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Would it make sense to make a `node-server` configuration upstream that includes all of the above and these `languageOptions`?  Ideally I think we'd like packages to use fully predefined configs as much as possible, while leaving the door open to customization for oddballs like Hubkit.
</blockquote></details>

How about now?

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`eslint.config.mjs` line 11 at r4](https://reviewable.io/reviews/Reviewable/nodefire/43#-O7onw8O6AOlFFVVRB1B:-O7q5cOI0ZVNrtK-uA4y:b-sqancb) ([raw file](https://github.com/Reviewable/nodefire/blob/80988d865df7ad455195b7dad24ddd266a390086/eslint.config.mjs#L11)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

How about now?
</blockquote></details>

Acceptable — let's see how many times we end up repeating these three lines and if it's worth factoring out.

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`package.json` line 42 at r1](https://reviewable.io/reviews/Reviewable/nodefire/43#-O77-Fsy5IS0xMgQmPJP:-O7t83324kFteudSVWxa:b-896fix) ([raw file](https://github.com/Reviewable/nodefire/blob/c37ff3cf46107fcdb636bf2a03509b118005e5b8/package.json#L42)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

TODO: Update once reviewable-config repo is published.
</blockquote></details>

Done.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/43)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Pull request merged**
