### PR TITLE
Add an assign() method to interpolate object properties for updates.

### PR DESCRIPTION
**Pull request by pkaminski**
This will make it easier to do update calls with multiple path scopes.  It will look something like this:

```js
const updates = {};
_.forEach(list, item => {
  db.scope({foo: item}).assign(updates, {
    'bar/:foo' : 'baz'
  });
});
db.update(updates);
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/30)

### CODE REVIEW

**Comment by pkaminski** [comment]
I'm having second thoughts about this new API -- it's a bit awkward to use in practice.  I'll send over the WIP on the server so you can see and perhaps we can come up with something better.

**Review by snoack — COMMENTED** [review]
Yeah, I was about to say something like that. At this point you could just do something like this instead:

```js
updates[db.interpolate(path, scope)] = value;
```

Which wouldn't be any more boilerplate than:

```js
updates.push({updates: [{path: value}], scope});
```

Initially, I was thinking we were just talking about supporting `db.update(updates, {scope})` which could be handy in a few simple update scenarios where we don't generate the updates from within a loop. If you want to make it more flexible though, how about a scope factory like this:

```js
const scope = db.scopeFactory();
const updates {};
_.forEach(organizations, org => {
  updates[`/organizationts/${scope.var(org)}/someOption`] = true;
});
db.update(updates, scope);
```

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/30#-:-NWrtKjb54iZQalTnKfq:b25jarf)* status: 0 of 1 files reviewed, all discussions resolved

**Review by snoack — COMMENTED** [review]
Then again, you could just use `NodeFire.escape` instead of a scope factory. Maybe there is still a case for `db.update(updates, {scope})` to help simpler scenarios but yeah anything more flexible doesn't seem worth it.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/30#-:-NWrxCfu8yuesFIczapp:b-5oj380)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by pkaminski** [comment]
The main use case for updates is multi-scoped paths.  (Single-scoped updates typically have non-variable paths anyway, so anything will be fine there.)  I was using the explicit `db.interpolate` pattern before but it's also rather clunky.  There's no need to add a scope to `update` since you can just do `db.scope({foo: 'bar'}).update(...)`.

PTAL at the new approach (with updated PR description).  It's simple, and I think it'll make the code even cleaner than the current JS template strings!

**Review by snoack — COMMENTED** [review]
No strong opinion on this approach. I tried it out in one instance, to get a feel for it:

```diff
--- a/src/payments.ts
+++ b/src/payments.ts
@@ -606,9 +606,10 @@ export async function syncSubscription(subscription) {
     // purposes of determining when another trial could start.
     const trialEndTimestamp = (subscription.ended_at ?? subscription.expiry) * 1000;
     _.forEach([organization, ...extraOrganizations], org => {
-      const orgKey = NodeFire.escape(org);
-      updates[`organizations/${orgKey}/coverage/trialEndTimestamp`] = trialEndTimestamp;
-      updates[`organizations/${orgKey}/coverage/lastWasTrial`] = false;
+      db.scope({orgKey: org}).assign(updates, {
+        'organizations/:orgKey/coverage/trialEndTimestamp': trialEndTimestamp,
+        'organizations/:orgKey/coverage/lastWasTrial': false,
+      });
     });
   }
```

But I can't really tell if I prefer `scope`+`assign` or `NodeFire.escape` + template string (or `interpolate`) in scenarios like that.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/30#-:-NWtGhlF-ZjyZu-6rIqR:bs47qu4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`src/nodefire.ts` line 185 at r2](https://reviewable.io/reviews/Reviewable/nodefire/30#-NWtGRaB4YDH6pnZsRR4:-NWtGRaB4YDH6pnZsRR5:undefined) ([raw file](https://github.com/Reviewable/nodefire/blob/45e08e1cc8447e8c8a269e2e69a4a7030137c3ca/src/nodefire.ts#L185)):*
> ```XML
>    * @returns The target object.
>    */
>   assign(target: any, source: any): any {
> ```





_Suggestion:_
```XML
assign(target: object, source: object): object
```

**Review by pkaminski — COMMENTED** [review]
I think of `escape` and `interpolate` as low-level primitives, whose usage should signal that something unusual is going on.  I think there's also a big consistency win in using the same kind of templates in `child` and `update` (via `assign`) calls, rather than bringing in template strings.

I went ahead and redid the fixes in `reviewable-server` using this approach and I believe it's a winner.  PTAL

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/30#-:-NWtJAeg9kz2RlajQHq5:b-dwht4n)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`src/nodefire.ts` line 185 at r2](https://reviewable.io/reviews/Reviewable/nodefire/30#-NWtGRaB4YDH6pnZsRR4:-NWtKF4P5BA5KyoqxZq9:b-896fix) ([raw file](https://github.com/Reviewable/nodefire/blob/45e08e1cc8447e8c8a269e2e69a4a7030137c3ca/src/nodefire.ts#L185)):*
> ```XML
>    * @returns The target object.
>    */
>   assign(target: any, source: any): any {
> ```

Done.

**Review by snoack — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Pull request merged**
