### PR TITLE
Add typescript type declarations

### PR DESCRIPTION
**Pull request by dhbradshaw**
This change is [Reviewable](https://reviewable.io/reviews/reviewable/nodefire/20)

### CODE REVIEW

**Review by pkaminski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/reviewable/nodefire/20)* status: all files reviewed, 10 unresolved discussions (waiting on @dhbradshaw)

___
*[nodefire.d.ts, line 33 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDTkaPAdrpHIHxwt71:-MHDTkaPAdrpHIHxwt72:bgt98ug) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L33)):*
> ```XML
>      *     interceptors) until the promise settles.
>      */
>     static interceptOperations(callback: Function): void;
> ```

`callback` is more like `(op: {ref: NodeFire, method: string, args: any[]}, options: any) => void | Promise<void>`.
___
*[nodefire.d.ts, line 83 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDPtxU11UWJUx722tr:-MHDPtxU11UWJUx722ts:b-1wnm15) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L83)):*
> ```XML
>      * @param {Object} scope Optional dictionary that will be used for interpolating paths.
>      */
>     constructor(ref: import("firebase-admin/lib/database").admin.database.Query, scope: any);
> ```

Shouldn't you just import `firebase-admin/lib/database` once at the top?
___
*[nodefire.d.ts, line 86 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDQlcd2Vtv5Uy6EbZY:-MHDQlcd2Vtv5Uy6EbZZ:b95qahc) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L86)):*
> ```XML
>     $ref: import("firebase-admin/lib/database").admin.database.Query;
>     $scope: any;
>     _path: string;
> ```

This is meant to be private -- are we accessing it directly from a client somewhere?  There's a public getter for external use.
___
*[nodefire.d.ts, line 140 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDQwNl9WBpUvG0t3m5:-MHDQwNl9WBpUvG0t3m6:bswobkp) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L140)):*
> ```XML
>      * @return {NodeFire} Another NodeFire instance against which to compare.
>      */
>     isEqual(otherRef: any): NodeFire;
> ```

That type signature doesn't look right.  I'd think it should be `isEqual(other: NodeFire): boolean`.
___
*[nodefire.d.ts, line 169 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDTKRh8y0fgLzJG1AF:-MHDTKRh8y0fgLzJG1AG:b-6dlpaf) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L169)):*
> ```XML
>      *     error.  The value returned is normalized, meaning arrays are converted to objects.
>      */
>     get(options: any): Promise<any>;
> ```

`options` are `{timeout: number?, cache: boolean?}`.
___
*[nodefire.d.ts, line 185 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDRENd-2Q7O6vA6KUQ:-MHDRENd-2Q7O6vA6KUR:b8ncuy8) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L185)):*
> ```XML
>      *     error.
>      */
>     set(value: any, options: any): Promise<any>;
> ```

Is it possible to declare this as `Promise<void>` as some such, to assert that no useful value is returned?  Or just declare the method as `async ... : void`?

Also, `options` here and below are `{timeout: number?}`.
___
*[nodefire.d.ts, line 231 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDSitoDIFKnUkNVr6y:-MHDSitoDIFKnUkNVr6z:b-oql0eu) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L231)):*
> ```XML
>      *     transaction committed or with undefined if it aborted, or rejected with an error.
>      */
>     transaction(updateFunction: (arg0: any) => any, options: any): Promise<any>;
> ```

`options` should be like `{detectStuck: boolean?, prefetchValue: boolean?, timeout: number?}`.
___
*[nodefire.d.ts, line 240 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDSZDYBYcoLK6KzE5f:-MHDSZDYBYcoLK6KzE5g:bl8b51w) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L240)):*
> ```XML
>      *   3) The child() method takes an optional extra scope parameter, just like NodeFire.child().
>      */
>     on(eventType: any, callback: any, cancelCallback: any, context: any): any;
> ```

Don't know if it's worth it, but you could declare NodeFire's `Snapshot` class here too, so you can declare the callback type properly.  And `cancelCallback` is `() => void`.  Also below.
___
*[nodefire.d.ts, line 265 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDRylP45rpYk8Znbec:-MHDRylP45rpYk8Znbed:b-yfpdio) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L265)):*
> ```XML
>      * @return A promise that resolves to an array of key strings.
>      */
>     childrenKeys(...args: any[]): any;
> ```

I think the arguments should be `{maxTries: number?, retryInterval: number?, agent: http.Agent?}`.  I added the `agent` option recently in `firebase-childrenkeys` and forgot to update the docs here.  Its type is the agent type from Node's `http` package.
___
*[nodefire.d.ts, line 277 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDRlxx-eXGNh86adOw:-MHDRlxx-eXGNh86adOx:bnlqr1t) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L277)):*
> ```XML
> }
> declare namespace NodeFire {
>     const LOG_TRANSACTIONS: boolean;
> ```

This is effectively a static property, any reason why it can't be declared as such?  (The JS class syntax doesn't support that, but I thought maybe TypeScript's does.)

**Review by dhbradshaw — COMMENTED** [review]
Looks like I failed to mention it in the comments, but this first pass was auto-generated by tsc

> *[Reviewable](https://reviewable.io/reviews/reviewable/nodefire/20#-:-MHH8CUq33HJyXYJazx4:b-c2knbh)* status: all files reviewed, 10 unresolved discussions (waiting on @dhbradshaw)

**Comment by pkaminski** [comment]
Oops, did I jump the gun on the review?  Sorry.

**Comment by dhbradshaw** [comment]
___
*[nodefire.d.ts, line 185 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDRENd-2Q7O6vA6KUQ:-MHNTtkZ7ECduFt_1Anz:b-nv6nto) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L185)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Is it possible to declare this as `Promise<void>` as some such, to assert that no useful value is returned?  Or just declare the method as `async ... : void`?

Also, `options` here and below are `{timeout: number?}`.
</blockquote></details>

In the past you've preferred `{timeout?: number}` to `{timeout: number?}`.  The former means either {timeout: number} or {} while the latter means `{timeout: number | null}`.  Do we want the latter here?

**Comment by pkaminski** [comment]
___
*[nodefire.d.ts, line 185 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDRENd-2Q7O6vA6KUQ:-MHN_PeJDrtafY0ufqfK:b-ffk10w) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L185)):*
<details><summary><i>Previously, dhbradshaw (Douglas H. Bradshaw) wrote…</i></summary><blockquote>

In the past you've preferred `{timeout?: number}` to `{timeout: number?}`.  The former means either {timeout: number} or {} while the latter means `{timeout: number | null}`.  Do we want the latter here? 
</blockquote></details>

Oops, my TypeScript-fu is weak.  I meant the former, and failed to even realize that they're different.  (Though really, `{timeout?: number?}` would be most accurate I guess...)

**Review by dhbradshaw — COMMENTED** [review]
These comments are useful one way or another and I'll take advantage of them.

For maintenance purposes, I think that this file should be generated and not maintained by hand.  I'll try to make the adaptions necessary to take your feedback into account by altering nodefire.js.

> *[Reviewable](https://reviewable.io/reviews/reviewable/nodefire/20#-:-MHNNYNl4Y1KBOUrwX5R:b-myiik7)* status: 0 of 11 files reviewed, 10 unresolved discussions (waiting on @pkaminski)

___
*[nodefire.d.ts, line 33 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDTkaPAdrpHIHxwt71:-MHN3o5V3qRslX2GtOOV:b-896fix) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L33)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

`callback` is more like `(op: {ref: NodeFire, method: string, args: any[]}, options: any) => void | Promise<void>`.
</blockquote></details>

Done.
___
*[nodefire.d.ts, line 83 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDPtxU11UWJUx722tr:-MHNO4--DvgdQe-QsrXL:bgck2z9) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L83)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Shouldn't you just import `firebase-admin/lib/database` once at the top?
</blockquote></details>

That makes sense and works by hand.  I don't know how to trigger this behavior in tsc though.
___
*[nodefire.d.ts, line 86 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDQlcd2Vtv5Uy6EbZY:-MHNOq5m5pSv8ahv-6_k:bb6un1j) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L86)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

This is meant to be private -- are we accessing it directly from a client somewhere?  There's a public getter for external use.
</blockquote></details>

Done
___
*[nodefire.d.ts, line 140 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDQwNl9WBpUvG0t3m5:-MHNPID91-sejKsPgOga:b-896fix) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L140)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

That type signature doesn't look right.  I'd think it should be `isEqual(other: NodeFire): boolean`.
</blockquote></details>

Done.
___
*[nodefire.d.ts, line 169 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDTKRh8y0fgLzJG1AF:-MHNSm4hDm9YbHP8FaWx:b-896fix) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L169)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

`options` are `{timeout: number?, cache: boolean?}`.
</blockquote></details>

Done.
___
*[nodefire.d.ts, line 185 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDRENd-2Q7O6vA6KUQ:-MHNedIM8KwbpOZ9cvDW:b-67urcu) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L185)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Oops, my TypeScript-fu is weak.  I meant the former, and failed to even realize that they're different.  (Though really, `{timeout?: number?}` would be most accurate I guess...)
</blockquote></details>

ok, I'll default to double question marks
___
*[nodefire.d.ts, line 231 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDSitoDIFKnUkNVr6y:-MHNUxfXDKwFebcIv2du:b-896fix) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L231)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

`options` should be like `{detectStuck: boolean?, prefetchValue: boolean?, timeout: number?}`.
</blockquote></details>

Done.
___
*[nodefire.d.ts, line 240 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDSZDYBYcoLK6KzE5f:-MHNXNo49UceRTW2evqp:b-z8m5so) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L240)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Don't know if it's worth it, but you could declare NodeFire's `Snapshot` class here too, so you can declare the callback type properly.  And `cancelCallback` is `() => void`.  Also below.
</blockquote></details>

What's the right type for the callback here?
___
*[nodefire.d.ts, line 265 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDRylP45rpYk8Znbec:-MHNbMZE3RDpQ75ct0Iv:b-896fix) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L265)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I think the arguments should be `{maxTries: number?, retryInterval: number?, agent: http.Agent?}`.  I added the `agent` option recently in `firebase-childrenkeys` and forgot to update the docs here.  Its type is the agent type from Node's `http` package.
</blockquote></details>

Done.
___
*[nodefire.d.ts, line 277 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDRlxx-eXGNh86adOw:-MHNcgfUD79bU7mXx_Qg:b-maj1sa) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L277)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

This is effectively a static property, any reason why it can't be declared as such?  (The JS class syntax doesn't support that, but I thought maybe TypeScript's does.)
</blockquote></details>

Typescript can definitely do that.  I'm not sure how to communicate it through jsdoc though.

**Review by pkaminski — CHANGES_REQUESTED** [review]
Agreed.  If we need to go beyond the autogenerated types then we should just switch the source to TS and generate the JS from it instead.

> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/reviewable/nodefire/20#-:-MHOJXZr4uq5EbycAU5X:b-hmt0dl)* status: all files reviewed, 9 unresolved discussions (waiting on @dhbradshaw)

___
*[nodefire.js, line 254 at r2](https://reviewable.io/reviews/reviewable/nodefire/20#-MHOJnxe0HurNrV-IH5o:-MHOJnxe0HurNrV-IH5p:bi49msc) ([raw file](https://github.com/reviewable/nodefire/blob/6dc707c385d5be6816e31c9814d65c95c1706849/nodefire.js#L254)):*
> ```JavaScript
>    * Sets the value at this reference.
>    * @param {Object || number || string || boolean} value The value to set.
>    * @param {{timeout?: number?}=} options
> ```

What does that trailing `=` do?
___
*[nodefire.js, line 885 at r2](https://reviewable.io/reviews/reviewable/nodefire/20#-MHOKccgCp-tE90OL4-_:-MHOKccgCp-tE90OL4-a:be9j364) ([raw file](https://github.com/reviewable/nodefire/blob/6dc707c385d5be6816e31c9814d65c95c1706849/nodefire.js#L885)):*
> ```JavaScript
> 
> module.exports = NodeFire;
> module.exports.SnapShot = Snapshot;
> ```

`SnapShot` -> `Snapshot`
___
*[package.json, line 5 at r2](https://reviewable.io/reviews/reviewable/nodefire/20#-MHOKqHyADLPwSS46oaV:-MHOKqHyADLPwSS46oaW:b-kmz8oh) ([raw file](https://github.com/reviewable/nodefire/blob/6dc707c385d5be6816e31c9814d65c95c1706849/package.json#L5)):*
> ```JSON
>   "version": "3.0.2",
>   "description": "A promise-centric Firebase library for NodeJS",
>   "main": "built/index.js",
> ```

I don't think we actually need (or want) to compile the main module or the tests with `tsc` -- it's been working fine as-is for a long time now.  Just generate the main module types if that's possible, and if not then `.gitignore` the rest of the files to avoid confusion.
___
*[tsconfig.json, line 13 at r2](https://reviewable.io/reviews/reviewable/nodefire/20#-MHOLD1kD6yIlETMO3_f:-MHOLD1kD6yIlETMO3_g:baxgcfz) ([raw file](https://github.com/reviewable/nodefire/blob/6dc707c385d5be6816e31c9814d65c95c1706849/tsconfig.json#L13)):*
> ```jsonc
>         "rootDir": "./" /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */,
>         "strict": false /* Enable all strict type-checking options. */,
>         "target": "ES5" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */,
> ```

FYI, since we're restricting the engine to `node` `>=8.0` in `package.json`, we could definitely target something higher here.
___
*[nodefire.d.ts, line 240 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDSZDYBYcoLK6KzE5f:-MHOLn-EE60t2GAahiwT:b-lwwkts) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L240)):*
<details><summary><i>Previously, dhbradshaw (Douglas H. Bradshaw) wrote…</i></summary><blockquote>

What's the right type for the callback here?
</blockquote></details>

You want to match https://firebase.google.com/docs/reference/js/firebase.database.Query#on.  Though it shows a return type of `any`, whereas I think it should be `void`.
___
*[nodefire.d.ts, line 265 at r1](https://reviewable.io/reviews/reviewable/nodefire/20#-MHDRylP45rpYk8Znbec:-MHOM1uXCluFIlEb_XVu:b-f6m2v1) ([raw file](https://github.com/reviewable/nodefire/blob/2bc179effbefac50d24d92f0ee3882dfbc9248ef/nodefire.d.ts#L265)):*
<details><summary><i>Previously, dhbradshaw (Douglas H. Bradshaw) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm, it still kept the `...args` for some reason, even though it's not in the JSDoc.  Oh well?
___
*[built/nodefire.d.ts, line 110 at r2](https://reviewable.io/reviews/reviewable/nodefire/20#-MHOLZBt9bwFCJZwuSPH:-MHOLZBt9bwFCJZwuSPI:b-qmn5v7) ([raw file](https://github.com/reviewable/nodefire/blob/6dc707c385d5be6816e31c9814d65c95c1706849/built/nodefire.d.ts#L110)):*
> ```XML
>      * @return {NodeFire|null} A NodeFire reference at the same location as this query or reference.
>      */
>     get ref(): import("./nodefire");
> ```

Uh, these return types got weird now.
___
*[built/nodefire.d.ts, line 315 at r2](https://reviewable.io/reviews/reviewable/nodefire/20#-MHOMSFKAhQCjyCQk4yi:-MHOMSFKAhQCjyCQk4yj:b1615aq) ([raw file](https://github.com/reviewable/nodefire/blob/6dc707c385d5be6816e31c9814d65c95c1706849/built/nodefire.d.ts#L315)):*
> ```XML
> declare class Snapshot {
>     constructor(snap: any, nodeFire: any);
>     $snap: any;
> ```

This is the original Firebase API snapshot.
___
*[built/nodefire.d.ts, line 316 at r2](https://reviewable.io/reviews/reviewable/nodefire/20#-MHOMPCq6vkH7lA8deev:-MHOMPCq6vkH7lA8deew:b-y9ff0y) ([raw file](https://github.com/reviewable/nodefire/blob/6dc707c385d5be6816e31c9814d65c95c1706849/built/nodefire.d.ts#L316)):*
> ```XML
>     constructor(snap: any, nodeFire: any);
>     $snap: any;
>     $nodeFire: any;
> ```

This is a `NodeFire`.
___
*[built/nodefire.d.ts, line 317 at r2](https://reviewable.io/reviews/reviewable/nodefire/20#-MHOMMta8s7VUX96uOmu:-MHOMMta8s7VUX96uOmv:b-yqyrqu) ([raw file](https://github.com/reviewable/nodefire/blob/6dc707c385d5be6816e31c9814d65c95c1706849/built/nodefire.d.ts#L317)):*
> ```XML
>     $snap: any;
>     $nodeFire: any;
>     get key(): any;
> ```

Keys are always strings.
___
*[built/nodefire.d.ts, line 320 at r2](https://reviewable.io/reviews/reviewable/nodefire/20#-MHOMUof6hncvfNqTakg:-MHOMUof6hncvfNqTakh:b5d92u6) ([raw file](https://github.com/reviewable/nodefire/blob/6dc707c385d5be6816e31c9814d65c95c1706849/built/nodefire.d.ts#L320)):*
> ```XML
>     get ref(): import("./nodefire");
>     val(): any;
>     child(path: any, scope: any): Snapshot;
> ```

Path is a string.
___
*[built/nodefire.d.ts, line 321 at r2](https://reviewable.io/reviews/reviewable/nodefire/20#-MHOMXNS5j2swW2d_Fho:-MHOMXNS5j2swW2d_Fhp:bla36ur) ([raw file](https://github.com/reviewable/nodefire/blob/6dc707c385d5be6816e31c9814d65c95c1706849/built/nodefire.d.ts#L321)):*
> ```XML
>     val(): any;
>     child(path: any, scope: any): Snapshot;
>     forEach(callback: any): void;
> ```

The callback needs a better type -- see the Firebase docs: https://firebase.google.com/docs/reference/js/firebase.database.DataSnapshot#foreach but with the NodeFire snapshot substituted for theirs.

**Comment by dhbradshaw** [comment]
I'm closing this since we converted the js to typescript instead in pull request https://github.com/Reviewable/nodefire/pull/21

**Pull request closed without merging**
