### PR TITLE
Properly type values stored in Firebase

### PR DESCRIPTION
**Pull request by snoack**
This prevents undefined (or functions) to be passed which would fail.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/32)

### CODE REVIEW

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/32)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`src/nodefire.ts` line 723 at r1](https://reviewable.io/reviews/Reviewable/nodefire/32#-NXWt-Te9Kjvym7cjX6i:-NXWt-Te9Kjvym7cjX6j:b7gk1aq) ([raw file](https://github.com/Reviewable/nodefire/blob/49dd65efcf29647051e5dad624612b529d94d43d/src/nodefire.ts#L723)):*
> ```XML
>   }
> 
>   endAt(value: PrimitiveValue, key?: string): NodeFire {
> ```

Now `startAt` and `endAt` match the signature of the underlying function in `firebase-admin`. Previously, we allowed to pass `undefined` but not `null` while the underlying implementation accepts`null` but not `undefined`.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Review by snoack — COMMENTED** [review]
I will wait to merge this until I have the related changes for `reviewable-server` ready.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/32#-:-NXWzCqm3iFZrdLxPJ6M:bxqt4b6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Review by snoack — COMMENTED** [review]
One downside I came across as I started adapting `reviewable-server` for these changes is that as we don't have types for most (if not all) data stored in Firebase, I'm now ending up casting all objects read from Firebase to `any` because you cannot access any properties of a "value" before assigning it to a more specific type (or `any`). In a project with complete type definitions this wouldn't be an issue as you would cast any data structures read from Firebase to the appropriate interface anyway. But in the case of `reviewable-server`, it will just add additional boilerplate to our loosely typed code base. Any thoughts?

There is also a possible compromise, that is to type `StoredValue` as `any` but keep the `Value` type. That way we don't have to touch any code reading data from Firebase but still get sensible type checks when storing data.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/32#-:-NXXt4ZfAgnR-nW859l2:b-5tbjua)* status: all files reviewed, 3 unresolved discussions (waiting on @pkaminski)

___
*[`src/nodefire.ts` line 15 at r2](https://reviewable.io/reviews/Reviewable/nodefire/32#-NXXr9z58uucIrk2jR-W:-NXXr9z58uucIrk2jR-X:bopneui) ([raw file](https://github.com/Reviewable/nodefire/blob/31113f87c4d7804faf627fa6afa2ba2af6bf26cc/src/nodefire.ts#L15)):*
> ```XML
> 
> export type PrimitiveValue = string | number | boolean | null;
> export type Value = PrimitiveValue | {[key: string]: Value};
> ```

I realized that defining the `Hash` type is redundant since I can apparently reference the current type inline.
___
*[`src/nodefire.ts` line 16 at r2](https://reviewable.io/reviews/Reviewable/nodefire/32#-NXXrPzM9c1dq7OaCDZL:-NXXrPzNAakYwSaopaci:b-jb67ln) ([raw file](https://github.com/Reviewable/nodefire/blob/31113f87c4d7804faf627fa6afa2ba2af6bf26cc/src/nodefire.ts#L16)):*
> ```XML
> export type PrimitiveValue = string | number | boolean | null;
> export type Value = PrimitiveValue | {[key: string]: Value};
> export type StoredValue = PrimitiveValue | {[key: string]: NonNullable<StoredValue>};
> ```

This is a specialized variant of a value that reflects that values read from Firebase never include objects with properties that are `null`.
___
*[`src/nodefire.ts` line 189 at r2](https://reviewable.io/reviews/Reviewable/nodefire/32#-NXXrooABXwoFywfg3WU:-NXXrooABXwoFywfg3WV:bwwltz0) ([raw file](https://github.com/Reviewable/nodefire/blob/31113f87c4d7804faf627fa6afa2ba2af6bf26cc/src/nodefire.ts#L189)):*
> ```XML
>   assign<T1 extends object, T2 extends object>(
>     target: T1, source: T2
>   ): {[key: string]: T1[keyof T1] | T2[keyof T2]} {
> ```

While at it I gave the return value of `assign` a more meaningful return type.  The return type is now typed as an object whose properties are typed as a union of all types used in the  properties of the two input object.

**Review by pkaminski — COMMENTED** [review]
That's sad but not terribly surprising -- TypeScript never fully lived up to its "incremental typing" promise IMO.  I'm strongly opposed to boilerplate and especially pervasive casting so the precise definition of `StoredValue` probably has to go.  (Or at least wait for better, more strongly-typed days -- perhaps one day we'll figure out a good approach to integrating TypeScript with our schema declarations, but that's a non-trivial R&D project.)  I think keeping `Value` could add value (pun intended!) so I'd be game to move forward with the compromise you suggest, as long as it doesn't add much boilerplate beyond the occasional `!`.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/32#-:-NXXx6T7DT7bGjRISDwl:b-rbx3xr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @snoack)

___
*[`src/nodefire.ts` line 16 at r2](https://reviewable.io/reviews/Reviewable/nodefire/32#-NXY8MrXB8dcexr9jguN:-NXY8MrXB8dcexr9jguO:bfc07nx) ([raw file](https://github.com/Reviewable/nodefire/blob/31113f87c4d7804faf627fa6afa2ba2af6bf26cc/src/nodefire.ts#L16)):*
> ```XML
> export type PrimitiveValue = string | number | boolean | null;
> export type Value = PrimitiveValue | {[key: string]: Value};
> export type StoredValue = PrimitiveValue | {[key: string]: NonNullable<StoredValue>};
> ```

You might want to keep the precise type in a comment, along with an explanation of why we decided not to use it.  Up to you.

**Review by snoack — COMMENTED** [review]
Bummer, done.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/32#-:-NXY94cHB8E3xeMaltbX:b7e5043)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @snoack)

___
*[`src/nodefire.ts` line 16 at r2](https://reviewable.io/reviews/Reviewable/nodefire/32#-NXY8MrXB8dcexr9jguN:-NXYB89PEnAfa8Yw3E-P:b-896fix) ([raw file](https://github.com/Reviewable/nodefire/blob/31113f87c4d7804faf627fa6afa2ba2af6bf26cc/src/nodefire.ts#L16)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

You might want to keep the precise type in a comment, along with an explanation of why we decided not to use it.  Up to you.
</blockquote></details>

Done.
___
*[`src/nodefire.ts` line 189 at r2](https://reviewable.io/reviews/Reviewable/nodefire/32#-NXXrooABXwoFywfg3WU:-NXY8kV17jQXOMJQAMlx:b-sapx9j) ([raw file](https://github.com/Reviewable/nodefire/blob/31113f87c4d7804faf627fa6afa2ba2af6bf26cc/src/nodefire.ts#L189)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

While at it I gave the return value of `assign` a more meaningful return type.  The return type is now typed as an object whose properties are typed as a union of all types used in the  properties of the two input object.
</blockquote></details>

I realized, we can actually be a tiny bit more precise here, since the keys of `target: T1`are unchanged.

**Review by pkaminski — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/32#-:-NXYDD0g17Rn5s00iTtw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Review by snoack — COMMENTED** [review]
It looks like we don't even need to change anything in`reviewable-server` now. Up to you if you still want to bump the major version. I'm uncertain whether I'd consider this a breaking change at this point.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/32#-:-NXYDRC96tg1PiqhF08w:b-r0cx1g)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Pull request merged**
