### PR TITLE
Use promise-timeout instead of rolling our own timeout in invoke()

### PR DESCRIPTION
**Pull request by fahhem**
From our email correspondence, so we can review in an actually useful tool (Reviewable!)

- - -
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/27)

### CODE REVIEW

**Review by fahhem — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/27)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`package.json` line 42 at r1](https://reviewable.io/reviews/Reviewable/nodefire/27#-NNCznyh5_RamAnHCvBp:-NNCznyiC8nDrtwRAyQ2:bg93tv9) ([raw file](https://github.com/Reviewable/nodefire/blob/6e02e64a8093f271f60db7e7eb8ae59341da3e57/package.json#L42)):*
> ```JSON
>     "lru-cache": "6.x",
>     "safe-timers": "1.x",
>     "promise-timeout": "1.3.0",
> ```

Oops, not valid json



_Suggestion:_
```JSON
    "promise-timeout": "1.3.0"
```

**Review by pkaminski — COMMENTED** [review]
Hmm, not seeing a big benefit in pulling in the dependency.  It does exactly what the code you're replacing did, except that it doesn't have the secondary `settled` safety in case something goes weird with the timer.  It may also break some code that relies on the literal `timeout` message at the moment, and I doubt it would fix the issue we observed.

The only thing I might steal from their code is creating the error outside the timeout function.  This may let it carry the stack of the original invocation.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/27#-:-NNDtReG9zHHP8b9npks:b-inqzcc)* status: 1 of 2 files reviewed, all discussions resolved

**Review by pkaminski — COMMENTED** [review]
I have no idea how I successfully import `Timout` though -- that's a typo.  It probably works because the package is pure JS and the type isn't used in any meaningful fashion.

Another thing about the new dependency is that it uses the built-in, unsafe timers.  It's quite unlikely we'd set a timeout of over 25 days (!) but I standardized on `safe-timers` throughout the code so I don't have to think about it.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/27#-:-NNDuy6SCWFK7B5Ehz6x:bpjj6un)* status: 1 of 2 files reviewed, all discussions resolved

**Review by fahhem — COMMENTED** [review]
I pulled in the dep to simplify things, but it's ~50 lines of code we can duplicate here. It's mainly a case of decomposing the code so each piece is easier to understand. The promise-timeout-equivalent is currently in the middle of a bunch of code that resolves multiple promises into 1, then catches errors a certain way.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/27#-:-NNDvnX39uqrtYpR4iAw:bjsk11j)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @pkaminski)

**Review by pkaminski — COMMENTED** [review]
Deleting 15 simple lines to pull in 50 just doesn't sound like a win to me.  Note also that the `transaction` method has its own timeout implementation, so you'd want to clean that one up too.

I really feel like the easy win here is 1) fix the typo and 2) extract the error creation to the outer scope to hopefully get better traces.  Bonus points if you can extract a `timeout` function that works properly in both locations.  This code has been tested in production over many years, so unless we can identify a weakness or likely bug, I'd rather stick with it than pull in something new.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/27#-:-NNDy97rDXLGXHl_FYyO:b-x5qvjh)* status: 1 of 2 files reviewed, all discussions resolved

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/27)* status: 1 of 2 files reviewed, all discussions resolved

**Pull request closed without merging**
