### PR TITLE
Fix typing across the board

### PR DESCRIPTION
**Pull request by fahhem**
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/28)

### CODE REVIEW

**Review by fahhem — COMMENTED** [review]
+@pkaminski Pulled some of this out of #27 and will remove it from there shortly

> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/28#-:-NNHvRxgESGjqKukKwor:b-1359wc)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @pkaminski)

**Comment by fahhem** [comment]
@SocketSecurity ignore protobufjs-cli@1.0.2

**Review by pkaminski — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/nodefire/28)* status: all files reviewed, 1 unresolved discussion (waiting on @fahhem)

___
*[`src/nodefire.ts` line 929 at r2](https://reviewable.io/reviews/reviewable/nodefire/28#-NNIuaHFE1SRLjvB-Lmn:-NNIuaHFE1SRLjvB-Lmo:bt4f7ky) ([raw file](https://github.com/reviewable/nodefire/blob/b00196047a17df7595e43993a0cfc8d5501516a2/src/nodefire.ts#L929)):*
> ```XML
>   if (argsString.length > 500) argsString = argsString.slice(0, 500) + '...';
>   error.firebase = {
>     ref: op.ref.toString(), method: op.method, argsString,
> ```

The idea here is to send the properly-structured `args` if it's short enough, since Sentry will do a better job of rendering them.  (These often contain nested objects, etc.)  We only want to fall back to stringified args if the raw structure gets too long and would get left out altogether, since something is better than nothing.

**Comment by fahhem** [comment]
*[`src/nodefire.ts` line 929 at r2](https://reviewable.io/reviews/Reviewable/nodefire/28#-NNIuaHFE1SRLjvB-Lmn:-NNIwwFKDP9biCyyM5LC:b-mn48b4) ([raw file](https://github.com/Reviewable/nodefire/blob/b00196047a17df7595e43993a0cfc8d5501516a2/src/nodefire.ts#L929)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

The idea here is to send the properly-structured `args` if it's short enough, since Sentry will do a better job of rendering them.  (These often contain nested objects, etc.)  We only want to fall back to stringified args if the raw structure gets too long and would get left out altogether, since something is better than nothing.
</blockquote></details>

Ah, I figured that was the case, but wasn't sure if it mattered if it was a string or string[] to sentry. I made it polymorphic again

**Comment by fahhem** [comment]
*[`src/nodefire.ts` line 929 at r2](https://reviewable.io/reviews/Reviewable/nodefire/28#-NNIuaHFE1SRLjvB-Lmn:-NNJjbBm0v5kKM8XEQfh:b-s3yhzb) ([raw file](https://github.com/Reviewable/nodefire/blob/b00196047a17df7595e43993a0cfc8d5501516a2/src/nodefire.ts#L929)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

`args` is actually `any[] | string` (or even `unknown[] | string`), if you want to be accurate.

Also, nit:  `args: args` --> `args` (might fail lint if it's set up the same here as in our main repos)

</blockquote></details>

I tried avoiding a separate variable, but keeping it as just `args` was honestly worse, so I went with `argsToSentry: any[]|string` so the typing is correct and at least a little useful.

**Review by pkaminski — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/28#-:-NNJkaSQ5ZiMZRmDplyN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fahhem)

___
*[`src/nodefire.ts` line 929 at r2](https://reviewable.io/reviews/Reviewable/nodefire/28#-NNIuaHFE1SRLjvB-Lmn:-NNJkNwD7g9ainmB_J83:bizrzsj) ([raw file](https://github.com/Reviewable/nodefire/blob/b00196047a17df7595e43993a0cfc8d5501516a2/src/nodefire.ts#L929)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

I tried avoiding a separate variable, but keeping it as just `args` was honestly worse, so I went with `argsToSentry: any[]|string` so the typing is correct and at least a little useful.
</blockquote></details>

Works for me.  (Normally, I'd use a `const` and a ternary to assign the value, but I'm guessing TypeScript doesn't like ternaries with different result types across its branches.)

**Review by fahhem — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/nodefire/28)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fahhem)

**Pull request merged**
